---
kind: pipeline
type: docker
name: components

steps:
  - name: build
    image: node:latest
    environment:
      NPM_CONFIG_USERCONFIG: /config/.npmrc
    volumes:
      - name: config
        path: /config
      - name: cache
        path: /npm
    commands:
      - cat /config/.npmrc
      - yarn install
      - yarn build

  - name: code-analysis
    image: committed/drone-sonarqube-node
    environment:
      SONAR_HOST:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token

  - name: publish
    image: node:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      NPM_CONFIG_USERCONFIG: /config/.npmrc
    volumes:
      - name: config
        path: /config
      - name: cache
        path: /npm
    commands:
      - yarn publish
      - yarn deploy-storybook --ci
    when:
      ref:
        - refs/tags/v*

  - name: slack
    image: plugins/slack
    webhook: <slack_webhook>
    settings:
      channel: group-ci
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure

volumes:
  - name: config
    host:
      path: /config
  - name: cache
    host:
      path: /cache/npm
