---
kind: pipeline
type: docker
name: components

steps:
  - name: build
    image: node:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: drone
        path: /drone
    commands:
      - . /drone/config/env
      - yarn install
      - yarn build

  - name: publish
    image: node:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: drone
        path: /drone
    commands:
      - . /drone/config/env
      - yarn publish
      - yarn deploy-storybook --ci
    when:
      ref:
        - refs/tags/v*

  - name: code-analysis
    image: committed/drone-sonarqube-node
    detach: true
    environment:
      SONAR_HOST:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token
    settings:
      exclusions: '**/node_modules/**/*,**/dist/**/*.js'

  - name: slack
    image: plugins/slack
    settings:
      channel: group-ci
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure

volumes:
  - name: drone
    host:
      path: /drone
