---
kind: pipeline
type: docker
name: components

steps:
  - name: npm_auth
    image: robertstettner/drone-npm-auth
    settings:
      token:
        from_secret: npm_token

  - name: build
    image: node:latest
    commands:
      - yarn install
      - yarn build

  - name: danger
    image: node:latest
    environment:
      DANGER_GITHUB_API_TOKEN:
        from_secret: github_token
    commands:
      - yarn danger ci
    when:
      event:
        - pull_request

  - name: publish
    image: node:latest
    environment:
      GH_TOKEN:
        from_secret: github_token
    commands:
      - npm publish --access public
      - yarn deploy-storybook --ci
    when:
      ref:
        - refs/tags/v*

  - name: code-analysis
    image: committed/drone-sonarqube-node
    environment:
      SONAR_HOST:
        from_secret: sonar_host
      SONAR_TOKEN:
        from_secret: sonar_token
    settings:
      exclusions: '**/node_modules/**/*,**/dist/**/*.js'
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: slack
    image: plugins/slack
    settings:
      channel: group-ci
      webhook:
        from_secret: slack_webhook
      template:
        from_secret: slack_template
    when:
      status:
        - failure

  - name: announce
    image: plugins/slack
    settings:
      channel: group-dev
      webhook:
        from_secret: slack_webhook
      template: >
        :tada: New version ${DRONE_TAG} of `@committed/components` available
    when:
      ref:
        - refs/tags/v*
      status:
        - success
