export const listOfCountries = [
  { title: 'Afghanistan' },
  { title: 'Albania' },
  { title: 'Algeria' },
  { title: 'Andorra' },
  { title: 'Angola' },
  { title: 'Anguilla' },
  { title: 'Antigua & Barbuda' },
  { title: 'Argentina' },
  { title: 'Armenia' },
  { title: 'Australia' },
  { title: 'Austria' },
  { title: 'Azerbaijan' },
  { title: 'Bahamas' },
  { title: 'Bahrain' },
  { title: 'Bangladesh' },
  { title: 'Barbados' },
  { title: 'Belarus' },
  { title: 'Belgium' },
  { title: 'Belize' },
  { title: 'Benin' },
  { title: 'Bermuda' },
  { title: 'Bhutan' },
  { title: 'Bolivia' },
  { title: 'Bosnia & Herzegovina' },
  { title: 'Botswana' },
  { title: 'Brazil' },
  { title: 'Brunei Darussalam' },
  { title: 'Bulgaria' },
  { title: 'Burkina Faso' },
  { title: 'Burundi' },
  { title: 'Cambodia' },
  { title: 'Cameroon' },
  { title: 'Canada' },
  { title: 'Cape Verde' },
  { title: 'Cayman Islands' },
  { title: 'Central African Republic' },
  { title: 'Chad' },
  { title: 'Chile' },
  { title: 'China' },
  { title: 'China - Hong Kong / Macau' },
  { title: 'Colombia' },
  { title: 'Comoros' },
  { title: 'Congo' },
  { title: 'Congo, Democratic Republic of (DRC)' },
  { title: 'Costa Rica' },
  { title: 'Croatia' },
  { title: 'Cuba' },
  { title: 'Cyprus' },
  { title: 'Czech Republic' },
  { title: 'Denmark' },
  { title: 'Djibouti' },
  { title: 'Dominica' },
  { title: 'Dominican Republic' },
  { title: 'Ecuador' },
  { title: 'Egypt' },
  { title: 'El Salvador' },
  { title: 'Equatorial Guinea' },
  { title: 'Eritrea' },
  { title: 'Estonia' },
  { title: 'Eswatini' },
  { title: 'Ethiopia' },
  { title: 'Fiji' },
  { title: 'Finland' },
  { title: 'France' },
  { title: 'French Guiana' },
  { title: 'Gabon' },
  { title: 'Gambia, Republic of The' },
  { title: 'Georgia' },
  { title: 'Germany' },
  { title: 'Ghana' },
  { title: 'Great Britain' },
  { title: 'Greece' },
  { title: 'Grenada' },
  { title: 'Guadeloupe' },
  { title: 'Guatemala' },
  { title: 'Guinea' },
  { title: 'Guinea-Bissau' },
  { title: 'Guyana' },
  { title: 'Haiti' },
  { title: 'Honduras' },
  { title: 'Hungary' },
  { title: 'Iceland' },
  { title: 'India' },
  { title: 'Indonesia' },
  { title: 'Iran' },
  { title: 'Iraq' },
  { title: 'Israel and the Occupied Territories' },
  { title: 'Italy' },
  { title: "Ivory Coast (Cote d'Ivoire)" },
  { title: 'Jamaica' },
  { title: 'Japan' },
  { title: 'Jordan' },
  { title: 'Kazakhstan' },
  { title: 'Kenya' },
  { title: 'Korea, Democratic Republic of (North Korea)' },
  { title: 'Korea, Republic of (South Korea)' },
  { title: 'Kosovo' },
  { title: 'Kuwait' },
  { title: 'Kyrgyz Republic (Kyrgyzstan)' },
  { title: 'Laos' },
  { title: 'Latvia' },
  { title: 'Lebanon' },
  { title: 'Lesotho' },
  { title: 'Liberia' },
  { title: 'Libya' },
  { title: 'Liechtenstein' },
  { title: 'Lithuania' },
  { title: 'Luxembourg' },
  { title: 'Madagascar' },
  { title: 'Malawi' },
  { title: 'Malaysia' },
  { title: 'Maldives' },
  { title: 'Mali' },
  { title: 'Malta' },
  { title: 'Martinique' },
  { title: 'Mauritania' },
  { title: 'Mauritius' },
  { title: 'Mayotte' },
  { title: 'Mexico' },
  { title: 'Moldova, Republic of' },
  { title: 'Monaco' },
  { title: 'Mongolia' },
  { title: 'Montenegro' },
  { title: 'Montserrat' },
  { title: 'Morocco' },
  { title: 'Mozambique' },
  { title: 'Myanmar/Burma' },
  { title: 'Namibia' },
  { title: 'Nepal' },
  { title: 'Netherlands' },
  { title: 'New Zealand' },
  { title: 'Nicaragua' },
  { title: 'Niger' },
  { title: 'Nigeria' },
  { title: 'North Macedonia, Republic of' },
  { title: 'Norway' },
  { title: 'Oman' },
  { title: 'Pacific Islands' },
  { title: 'Pakistan' },
  { title: 'Panama' },
  { title: 'Papua New Guinea' },
  { title: 'Paraguay' },
  { title: 'Peru' },
  { title: 'Philippines' },
  { title: 'Poland' },
  { title: 'Portugal' },
  { title: 'Puerto Rico' },
  { title: 'Qatar' },
  { title: 'Reunion' },
  { title: 'Romania' },
  { title: 'Russian Federation' },
  { title: 'Rwanda' },
  { title: 'Saint Kitts and Nevis' },
  { title: 'Saint Lucia' },
  { title: 'Saint Vincent and the Grenadines' },
  { title: 'Samoa' },
  { title: 'Sao Tome and Principe' },
  { title: 'Saudi Arabia' },
  { title: 'Senegal' },
  { title: 'Serbia' },
  { title: 'Seychelles' },
  { title: 'Sierra Leone' },
  { title: 'Singapore' },
  { title: 'Slovak Republic (Slovakia)' },
  { title: 'Slovenia' },
  { title: 'Solomon Islands' },
  { title: 'Somalia' },
  { title: 'South Africa' },
  { title: 'South Sudan' },
  { title: 'Spain' },
  { title: 'Sri Lanka' },
  { title: 'Sudan' },
  { title: 'Suriname' },
  { title: 'Sweden' },
  { title: 'Switzerland' },
  { title: 'Syria' },
  { title: 'Tajikistan' },
  { title: 'Tanzania' },
  { title: 'Thailand' },
  { title: 'Timor Leste' },
  { title: 'Togo' },
  { title: 'Trinidad & Tobago' },
  { title: 'Tunisia' },
  { title: 'Turkey' },
  { title: 'Turkmenistan' },
  { title: 'Turks & Caicos Islands' },
  { title: 'Uganda' },
  { title: 'Ukraine' },
  { title: 'United Arab Emirates' },
  { title: 'United States of America (USA)' },
  { title: 'Uruguay' },
  { title: 'Uzbekistan' },
  { title: 'Venezuela' },
  { title: 'Vietnam' },
  { title: 'Virgin Islands (UK)' },
  { title: 'Virgin Islands (US)' },
  { title: 'Yemen' },
  { title: 'Zambia' },
  { title: 'Zimbabwe' },
]
