export { Theme } from '@material-ui/core/styles/createMuiTheme'
export * as colors from './colors'
export * from './darkTheme'
export * as fonts from './fonts'
export * from './lightTheme'
export * as theme from './theme'
export * from './ThemeProvider'
export { ThemeSwitch } from './ThemeSwitch'
export type { ThemeSwitchProps } from './ThemeSwitch'
export * from './types'
export { useThemeChoice } from './useThemeChoice'
export * from './createTheme'
