name: CI

on:   
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: Borales/actions-yarn@master
        run: install
      - uses: Borales/actions-yarn@master
        run: build
