name: build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, lint, test, sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install deps and build (with cache)
        if: ${{ !env.ACT }}
        uses: bahmutov/npm-install@v1

      - name: Full Install
        if: ${{ env.ACT }}
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Danger
        run: npm run danger -- ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: npm test -- --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook --quiet

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
