name: release

on:
  release:
    types: [created]

jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: Install with cache
        if: ${{ !env.ACT }}
        uses: bahmutov/npm-install@v1

      - name: Full Install
        if: ${{ env.ACT }}
        run: npm install

      - name: Publish Package
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Docs
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
