name: release

on:
  push:
    branches:
      - main
      - beta

jobs:
  build:
    name: Full CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: Install with cache
        if: ${{ !env.ACT }}
        uses: bahmutov/npm-install@v1

      - name: Full Install
        if: ${{ env.ACT }}
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook -- --quiet

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Publish Docs
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
